# Generated by Django 5.2.5 on 2025-09-05 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Calories_history',
            new_name='history',
        ),
    ]
